# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'templates\MainWindow.ui'
#
# Created: Fri Mar  1 13:32:37 2019
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(928, 654)
        MainWindow.setMinimumSize(QtCore.QSize(20, 60))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.addButton = QtGui.QPushButton(self.centralwidget)
        self.addButton.setObjectName("addButton")
        self.gridLayout.addWidget(self.addButton, 1, 0, 1, 1)
        self.removeButton = QtGui.QPushButton(self.centralwidget)
        self.removeButton.setObjectName("removeButton")
        self.gridLayout.addWidget(self.removeButton, 1, 1, 1, 1)
        self.projetcList = QtGui.QListWidget(self.centralwidget)
        self.projetcList.setObjectName("projetcList")
        self.gridLayout.addWidget(self.projetcList, 0, 0, 1, 2)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Src = QtGui.QLabel(self.frame)
        self.Src.setObjectName("Src")
        self.gridLayout_2.addWidget(self.Src, 1, 0, 1, 1)
        self.SrcPath = QtGui.QLineEdit(self.frame)
        self.SrcPath.setObjectName("SrcPath")
        self.gridLayout_2.addWidget(self.SrcPath, 1, 1, 1, 2)
        self.add_src_path_button = QtGui.QPushButton(self.frame)
        self.add_src_path_button.setMaximumSize(QtCore.QSize(16777215, 1000))
        self.add_src_path_button.setObjectName("add_src_path_button")
        self.gridLayout_2.addWidget(self.add_src_path_button, 1, 3, 1, 1)
        self.Dest = QtGui.QLabel(self.frame)
        self.Dest.setObjectName("Dest")
        self.gridLayout_2.addWidget(self.Dest, 2, 0, 1, 1)
        self.DestPath = QtGui.QLineEdit(self.frame)
        self.DestPath.setObjectName("DestPath")
        self.gridLayout_2.addWidget(self.DestPath, 2, 1, 1, 2)
        self.add_dest_path_button = QtGui.QPushButton(self.frame)
        self.add_dest_path_button.setMaximumSize(QtCore.QSize(16777215, 100))
        self.add_dest_path_button.setObjectName("add_dest_path_button")
        self.gridLayout_2.addWidget(self.add_dest_path_button, 2, 3, 1, 1)
        self.label = QtGui.QLabel(self.frame)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.ProjectNameLine = QtGui.QLineEdit(self.frame)
        self.ProjectNameLine.setObjectName("ProjectNameLine")
        self.gridLayout_2.addWidget(self.ProjectNameLine, 0, 1, 1, 3)
        self.verticalLayout_3.addLayout(self.gridLayout_2)
        self.groupBox = QtGui.QGroupBox(self.frame)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.FileMaskLabel = QtGui.QLabel(self.groupBox)
        self.FileMaskLabel.setObjectName("FileMaskLabel")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.FileMaskLabel)
        self.FileMaskLine = QtGui.QLineEdit(self.groupBox)
        self.FileMaskLine.setObjectName("FileMaskLine")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.FileMaskLine)
        self.horizontalLayout_2.addLayout(self.formLayout_2)
        self.setFilesMaskButton = QtGui.QPushButton(self.groupBox)
        self.setFilesMaskButton.setObjectName("setFilesMaskButton")
        self.horizontalLayout_2.addWidget(self.setFilesMaskButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.formLayout_3 = QtGui.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_2)
        self.TimePereodSpinBox = QtGui.QSpinBox(self.groupBox)
        self.TimePereodSpinBox.setObjectName("TimePereodSpinBox")
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.TimePereodSpinBox)
        self.horizontalLayout_3.addLayout(self.formLayout_3)
        self.formLayout_4 = QtGui.QFormLayout()
        self.formLayout_4.setObjectName("formLayout_4")
        self.Time = QtGui.QLabel(self.groupBox)
        self.Time.setObjectName("Time")
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.Time)
        self.TimeToLiveSpinBox = QtGui.QSpinBox(self.groupBox)
        self.TimeToLiveSpinBox.setObjectName("TimeToLiveSpinBox")
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.TimeToLiveSpinBox)
        self.horizontalLayout_3.addLayout(self.formLayout_4)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.frame)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout_5 = QtGui.QFormLayout()
        self.formLayout_5.setObjectName("formLayout_5")
        self.Src_2 = QtGui.QLabel(self.groupBox_2)
        self.Src_2.setObjectName("Src_2")
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.LabelRole, self.Src_2)
        self.DirectoryMask = QtGui.QLineEdit(self.groupBox_2)
        self.DirectoryMask.setObjectName("DirectoryMask")
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.FieldRole, self.DirectoryMask)
        self.Dest_2 = QtGui.QLabel(self.groupBox_2)
        self.Dest_2.setObjectName("Dest_2")
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.LabelRole, self.Dest_2)
        self.DestPath_2 = QtGui.QLineEdit(self.groupBox_2)
        self.DestPath_2.setObjectName("DestPath_2")
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.FieldRole, self.DestPath_2)
        self.verticalLayout_2.addLayout(self.formLayout_5)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.backupButton = QtGui.QPushButton(self.frame)
        self.backupButton.setObjectName("backupButton")
        self.verticalLayout_3.addWidget(self.backupButton)
        self.buttonBox = QtGui.QDialogButtonBox(self.frame)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_3.addWidget(self.buttonBox)
        self.horizontalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 928, 21))
        self.menubar.setObjectName("menubar")
        self.menufile = QtGui.QMenu(self.menubar)
        self.menufile.setObjectName("menufile")
        self.menuedit = QtGui.QMenu(self.menubar)
        self.menuedit.setObjectName("menuedit")
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAdd = QtGui.QAction(MainWindow)
        self.actionAdd.setObjectName("actionAdd")
        self.actionremove = QtGui.QAction(MainWindow)
        self.actionremove.setObjectName("actionremove")
        self.menufile.addAction(self.actionAdd)
        self.menufile.addAction(self.actionremove)
        self.menubar.addAction(self.menufile.menuAction())
        self.menubar.addAction(self.menuedit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.addButton.setText(QtGui.QApplication.translate("MainWindow", "AddButton", None, QtGui.QApplication.UnicodeUTF8))
        self.removeButton.setText(QtGui.QApplication.translate("MainWindow", "RemoveButton", None, QtGui.QApplication.UnicodeUTF8))
        self.Src.setText(QtGui.QApplication.translate("MainWindow", "Src", None, QtGui.QApplication.UnicodeUTF8))
        self.add_src_path_button.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.Dest.setText(QtGui.QApplication.translate("MainWindow", "Dest", None, QtGui.QApplication.UnicodeUTF8))
        self.add_dest_path_button.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Project Name", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "GroupBox", None, QtGui.QApplication.UnicodeUTF8))
        self.FileMaskLabel.setText(QtGui.QApplication.translate("MainWindow", "FileMask", None, QtGui.QApplication.UnicodeUTF8))
        self.setFilesMaskButton.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "TimePereod", None, QtGui.QApplication.UnicodeUTF8))
        self.Time.setText(QtGui.QApplication.translate("MainWindow", "TimeToLive", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "GroupBox", None, QtGui.QApplication.UnicodeUTF8))
        self.Src_2.setText(QtGui.QApplication.translate("MainWindow", "DirectoryMask", None, QtGui.QApplication.UnicodeUTF8))
        self.Dest_2.setText(QtGui.QApplication.translate("MainWindow", "path", None, QtGui.QApplication.UnicodeUTF8))
        self.backupButton.setText(QtGui.QApplication.translate("MainWindow", "BackUP", None, QtGui.QApplication.UnicodeUTF8))
        self.menufile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuedit.setTitle(QtGui.QApplication.translate("MainWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.menuView.setTitle(QtGui.QApplication.translate("MainWindow", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAdd.setText(QtGui.QApplication.translate("MainWindow", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.actionremove.setText(QtGui.QApplication.translate("MainWindow", "remove", None, QtGui.QApplication.UnicodeUTF8))

