# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'templates/MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(902, 680)
        MainWindow.setMinimumSize(QtCore.QSize(20, 60))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.addButton = QtWidgets.QPushButton(self.centralwidget)
        self.addButton.setObjectName("addButton")
        self.gridLayout.addWidget(self.addButton, 1, 0, 1, 1)
        self.removeButton = QtWidgets.QPushButton(self.centralwidget)
        self.removeButton.setObjectName("removeButton")
        self.gridLayout.addWidget(self.removeButton, 1, 1, 1, 1)
        self.projetcList = QtWidgets.QListWidget(self.centralwidget)
        self.projetcList.setObjectName("projetcList")
        self.gridLayout.addWidget(self.projetcList, 0, 0, 1, 2)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Src = QtWidgets.QLabel(self.frame)
        self.Src.setObjectName("Src")
        self.gridLayout_2.addWidget(self.Src, 1, 0, 1, 1)
        self.SrcPath = QtWidgets.QLineEdit(self.frame)
        self.SrcPath.setObjectName("SrcPath")
        self.gridLayout_2.addWidget(self.SrcPath, 1, 1, 1, 2)
        self.add_src_path_button = QtWidgets.QPushButton(self.frame)
        self.add_src_path_button.setMaximumSize(QtCore.QSize(16777215, 1000))
        self.add_src_path_button.setObjectName("add_src_path_button")
        self.gridLayout_2.addWidget(self.add_src_path_button, 1, 3, 1, 1)
        self.Dest = QtWidgets.QLabel(self.frame)
        self.Dest.setObjectName("Dest")
        self.gridLayout_2.addWidget(self.Dest, 2, 0, 1, 1)
        self.DestPath = QtWidgets.QLineEdit(self.frame)
        self.DestPath.setObjectName("DestPath")
        self.gridLayout_2.addWidget(self.DestPath, 2, 1, 1, 2)
        self.add_dest_path_button = QtWidgets.QPushButton(self.frame)
        self.add_dest_path_button.setMaximumSize(QtCore.QSize(16777215, 100))
        self.add_dest_path_button.setObjectName("add_dest_path_button")
        self.gridLayout_2.addWidget(self.add_dest_path_button, 2, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.ProjectNameLine = QtWidgets.QLineEdit(self.frame)
        self.ProjectNameLine.setObjectName("ProjectNameLine")
        self.gridLayout_2.addWidget(self.ProjectNameLine, 0, 1, 1, 3)
        self.verticalLayout_3.addLayout(self.gridLayout_2)
        self.groupBox = QtWidgets.QGroupBox(self.frame)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Include_Type_Label = QtWidgets.QLabel(self.groupBox)
        self.Include_Type_Label.setObjectName("Include_Type_Label")
        self.horizontalLayout_2.addWidget(self.Include_Type_Label)
        self.Include_Type_lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.Include_Type_lineEdit.setObjectName("Include_Type_lineEdit")
        self.horizontalLayout_2.addWidget(self.Include_Type_lineEdit)
        self.Include_Type_Button = QtWidgets.QPushButton(self.groupBox)
        self.Include_Type_Button.setObjectName("Include_Type_Button")
        self.horizontalLayout_2.addWidget(self.Include_Type_Button)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Exclude_Type_Label = QtWidgets.QLabel(self.groupBox)
        self.Exclude_Type_Label.setObjectName("Exclude_Type_Label")
        self.horizontalLayout_3.addWidget(self.Exclude_Type_Label)
        self.Exclude_Type_lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.Exclude_Type_lineEdit.setObjectName("Exclude_Type_lineEdit")
        self.horizontalLayout_3.addWidget(self.Exclude_Type_lineEdit)
        self.Exclude_Type_Button = QtWidgets.QPushButton(self.groupBox)
        self.Exclude_Type_Button.setObjectName("Exclude_Type_Button")
        self.horizontalLayout_3.addWidget(self.Exclude_Type_Button)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.backupButton = QtWidgets.QPushButton(self.frame)
        self.backupButton.setObjectName("backupButton")
        self.verticalLayout_3.addWidget(self.backupButton)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.frame)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_3.addWidget(self.buttonBox)
        self.horizontalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 902, 22))
        self.menubar.setObjectName("menubar")
        self.menufile = QtWidgets.QMenu(self.menubar)
        self.menufile.setObjectName("menufile")
        self.menuedit = QtWidgets.QMenu(self.menubar)
        self.menuedit.setObjectName("menuedit")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAdd = QtWidgets.QAction(MainWindow)
        self.actionAdd.setObjectName("actionAdd")
        self.actionremove = QtWidgets.QAction(MainWindow)
        self.actionremove.setObjectName("actionremove")
        self.menufile.addAction(self.actionAdd)
        self.menufile.addAction(self.actionremove)
        self.menubar.addAction(self.menufile.menuAction())
        self.menubar.addAction(self.menuedit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.addButton.setText(_translate("MainWindow", "AddButton"))
        self.removeButton.setText(_translate("MainWindow", "RemoveButton"))
        self.Src.setText(_translate("MainWindow", "Src"))
        self.add_src_path_button.setText(_translate("MainWindow", "..."))
        self.Dest.setText(_translate("MainWindow", "Dest"))
        self.add_dest_path_button.setText(_translate("MainWindow", "..."))
        self.label.setText(_translate("MainWindow", "Project Name"))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox"))
        self.Include_Type_Label.setText(_translate("MainWindow", "Include File Types"))
        self.Include_Type_Button.setText(_translate("MainWindow", "..."))
        self.Exclude_Type_Label.setText(_translate("MainWindow", "Exclude File Types"))
        self.Exclude_Type_Button.setText(_translate("MainWindow", "..."))
        self.backupButton.setText(_translate("MainWindow", "BackUP"))
        self.menufile.setTitle(_translate("MainWindow", "File"))
        self.menuedit.setTitle(_translate("MainWindow", "Edit"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.actionAdd.setText(_translate("MainWindow", "Add"))
        self.actionremove.setText(_translate("MainWindow", "remove"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
